# fly.toml app configuration file generated for wispy-moon-1671 on 2023-09-12T12:22:51-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "wispy-moon-1671"
primary_region = "mia"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]